version: "3.9"
services:
  app:
    container_name: app
    restart: always
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      REDIS_PASSWORD: redis
    links:
      - cache
      - db
    volumes:
      - ./:/src
  cache:
    container_name: redis
    image: redis:latest
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - cache:/data
  db:
    container_name: db
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  cache:
    driver: local
  db-data:
    driver: local