version: "3.9"
services:
  app:
    container_name: app
    restart: always
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      cache:
        condition: service_healthy
  cache:
    container_name: redis
    image: redis:latest
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local