basePath: /
definitions:
  http.ErrResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  http.IncrementRequest:
    properties:
      key:
        type: string
      value:
        type: integer
    type: object
  http.SaveValueRequest:
    properties:
      key:
        type: string
      value: {}
    type: object
  http.SignRequest:
    properties:
      key:
        type: string
      text:
        type: string
    type: object
  http.ValueIncrementResponse:
    properties:
      value:
        type: integer
    type: object
  http.ValueResponse:
    properties:
      value: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: Service use Redis
  title: Zen Mobile Service
  version: "0.1"
paths:
  /redis/:
    post:
      consumes:
      - application/json
      description: Saving a new key with a value
      parameters:
      - description: 'json request: save value'
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.SaveValueRequest'
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrResponse'
      summary: SaveValueByKey
      tags:
      - Redis
  /redis/{key}:
    get:
      description: Getting value by key
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.ValueResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrResponse'
      summary: ReadValueByKey
      tags:
      - Redis
  /redis/incr:
    post:
      consumes:
      - application/json
      description: Increment value by key if value is stored input redis
      parameters:
      - description: 'json request: increment value by key'
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.IncrementRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.ValueIncrementResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrResponse'
      summary: IncrementValueByKey
      tags:
      - Redis
  /sign/hmacsha512:
    post:
      consumes:
      - application/json
      description: Signature message
      parameters:
      - description: 'json request: signature text, key'
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/http.SignRequest'
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrResponse'
      summary: SignMessage
      tags:
      - Signature
swagger: "2.0"
